import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e1e3e4',
        'primary-container': '#002d52',
        'on-primary-fixed-variant': '#25486f',
        'on-error': '#ffffff',
        'on-primary-fixed': '#001c37',
        'on-error-container': '#93000a',
        'on-surface-variant': '#43474e',
        'on-surface': '#191c1d',
        'on-primary-container': '#7495c0',
        secondary: '#3f6653',
        'secondary-fixed-dim': '#a5d0b9',
        'inverse-surface': '#2e3132',
        'surface-bright': '#f8fafb',
        outline: '#73777f',
        'on-background': '#191c1d',
        'surface-tint': '#3f6088',
        'on-secondary-fixed': '#002114',
        'surface-variant': '#e1e3e4',
        'inverse-on-surface': '#eff1f2',
        'secondary-fixed': '#c1ecd4',
        primary: '#001830',
        'on-primary': '#ffffff',
        'inverse-primary': '#a7c9f6',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e6e8e9',
        surface: '#f8fafb',
        'primary-fixed-dim': '#a7c9f6',
        'surface-container': '#eceeef',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#5d4201',
        tertiary: '#211500',
        'tertiary-container': '#3b2900',
        'secondary-container': '#beead1',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#e9c176',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#274e3d',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f5',
        'on-tertiary-fixed': '#261900',
        'on-secondary-container': '#436b58',
        'surface-dim': '#d8dadb',
        background: '#f8fafb',
        'primary-fixed': '#d2e4ff',
        'outline-variant': '#c3c6cf',
        'tertiary-fixed': '#ffdea5',
        'on-tertiary-container': '#b18e49',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};

export default config;
